name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  # Windows
  windows-build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSVC dev environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@81f46b36426f4ccdc1c0e7ab48109f3c98cfdc81
      with:
        version: 1.3.243.0

    - name: Configure CMake
      run: cmake --preset x64-release

    - name: Build
      run: cmake --build --preset x64-release-build

    - name: Test
      run: ctest --preset x64-release-tests

  # Mac OS
  macos-build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@81f46b36426f4ccdc1c0e7ab48109f3c98cfdc81
      with:
        version: 1.3.243.0

    - name: Configure CMake
      run: cmake --preset macos-release
      env:
        CXX: g++-12

    - name: Build
      run: cmake --build --preset macos-release-build

    - name: Test
      run: ctest --preset macos-release-tests

  # Ubuntu
  ubuntu-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install platform-specific dependencies
      run: |
        sudo apt update
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@81f46b36426f4ccdc1c0e7ab48109f3c98cfdc81
      with:
        version: 1.3.243.0

    - name: Configure CMake
      run: cmake --preset linux-release
      env:
        CXX: g++-12

    - name: Build
      run: cmake --build --preset linux-release-build

    - name: Test
      run: ctest --preset linux-release-tests
