name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  # Windows
  windows-build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSVC dev environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset x64-release

    - name: Build
      run: cmake --build --preset x64-release-build

    - name: Test
      run: ctest --preset x64-release-tests

  # Mac OS
  macos-build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset macos-release
    - name: Build
      run: cmake --build --preset macos-release-build

    - name: Test
      run: ctest --preset macos-release-tests

  # Ubuntu
  ubuntu-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset linux-release
    - name: Build
      run: cmake --build --preset linux-release-build

    - name: Test
      run: ctest --preset linux-release-tests
